### ISSUE TITLE
Suggest to loosen the dependency on requests

### ISSUE THREAD

**Issue by Agnes-U** [mahdizojaji/TweetTel#16]
Hi, your project TweetTel(commit id: a81dcd936df12c429754b038f5481d4dc545a78e) requires "requests==2.27.1" in its dependency. After analyzing the source code, we found that the following versions of requests can also be suitable, i.e., requests 2.26.0, 2.27.0, since all functions that you directly (3 APIs: requests.api.get, requests.adapters.HTTPAdapter.__init__, requests.sessions.Session.__init__) or indirectly (propagate to 12 requests's internal APIs and 5 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on requests from "requests==2.27.1" to "requests>=2.26.0,<=2.27.1". This will improve the applicability of TweetTel and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on requests?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by mahdizojaji** [comment]
Hello, yes, it may be useful
But when users use virtualenv or other isolated package tools, they may not encounter conflict problems.

**Comment by Agnes-U** [comment]
Thanks for your reply. [ad100b](https://github.com/mahdizojaji/TweetTel/commit/ad100b33e2fd9b059695c36a5ccd1a40552592a4)
